# Generated by Django 4.2.5 on 2023-12-19 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_post_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
