# Generated by Django 3.2.23 on 2023-12-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_voted_users_choice_voted_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voted_users',
        ),
        migrations.AddField(
            model_name='profile',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_choices', to='main.Post'),
        ),
    ]
